<?php
    /** @var umiTemplaterPHP|sitePhpExtension $this */
    /** @var array $variables */
?>

<li>
    <a href="<?=$this->getHomePageUrl()?>" class="mt-burger"><span></span></a>
    <div class="mt-burger-menu">
        <?php foreach ($variables['item'] ?? [] as $item) :
            $active = !empty($item['status']) ? 'class="active"' : '';
            ?>
        <span><a href="<?=$item['link']?>" <?=$active;?>><?=$item['text']?></a></span>
        <?php endforeach; ?>
    </div>
</li>
