<?php
    /** @var umiTemplaterPHP|sitePhpExtension $this */
    /** @var array $variables */
    /** @var umiHierarchyElement $page */

    $page = $variables['page'];
?>

<?php if (preg_match('~cabinet~', $this->getCommonVar('request_uri'))) :
    echo $this->render($variables, 'modules/content/content/cabinet/default');
else :
    $sdt = $this->isSpecialPageDataType($page);

    switch (true) {
        case $page->getValue('use_named_template'):
            echo $this->render($variables, $this->getNamedTemplate($variables));
            break;
        case $sdt && $sdt['status']:
            echo $this->render($variables, $sdt['template']);
            break;
        default:
            echo $page->getValue('content');
    }
endif; ?>