<?php
    /** @var umiTemplaterPHP|sitePhpExtension $this */
    /** @var array $variables */
    /** @var umiHierarchyElement $page */

    $page = $variables['page'];
    $parent = $this->getPageById($page->getParentId());
?>

<?php if (preg_match('~cabinet~', $this->getCommonVar('request_uri'))) : ?>

    <?= $this->render($variables, 'modules/content/content/cabinet/default'); ?>

<?php else : ?>

    <?php if ($page->getValue('use_named_template')) {
        echo $this->render($variables, $this->getNamedTemplate($variables));
    } elseif (($sdt = $this->isSpecialPageDataType($page)) && $sdt['status']) {
        echo $this->render($variables, $sdt['template']);
    } else {
        echo $page->getValue('content');
    } ?>

<?php endif; ?>