<?php
    /** @var umiTemplaterPHP|sitePhpExtension $this */
    /** @var array $variables */

    $userId = \UmiCms\Service::Auth()->getUserId();
?>

<div class="data-block block-right">
    <p class="account-title-default">Контактная информация</p>
    <div class="info-wrap">

    </div>

    <div class="info-inputs">

    </div>

    <a href="#" class="edit-btn">Редактировать</a>

    <div class="edit-mode-btns">
        <a href="#" class="save-btn">Сохранить</a>
        <a href="#" class="cancel-changes">Отмена</a>
    </div>
</div>

